(()=>{
'use strict';
const $=id=>document.getElementById(id);
const video=$('video'),canvas=$('overlay'),ctx=canvas.getContext('2d');
const start=$('start'),startBtn=$('startBtn'),startText=$('startText'),hud=$('hud');
const cameraState=$('cameraState'),aiState=$('aiState'),speedEl=$('speed'),headingEl=$('heading'),countEl=$('count');
const alertEl=$('alert'),flash=$('flash'),soundToggle=$('soundToggle'),zoomToggle=$('zoomToggle');
const diag=$('diag'),diagText=$('diagText');

let stream=null, facingMode='environment', model=null, predictions=[], detectBusy=false, detectTimer=null;
let gps={speed:null,heading:null,accuracy:null,lat:null,lon:null}, orient={alpha:null,beta:null,gamma:null};
let watchId=null, lastFix=null, cameraError='', aiError='', geoError='', sensorError='', audioError='';
let audioContext=null,audioEnabled=true,lastBeep=0,lastRed=false;
const ZOOMS=[1,1.35,1.7,2]; let cameraZoom=1.35,focusZoom=1.35,focusPan={x:0,y:0},dangerBox=null,dangerSeenAt=0;
let cameraLog=[];

const relevant=new Set(['person','bicycle','car','motorcycle','bus','truck','dog','cat','horse','sheep','cow','elephant','bear','zebra','giraffe']);
const labels={person:'PERSONA',bicycle:'BICICLETA',car:'AUTO',motorcycle:'MOTO',bus:'BUS',truck:'CAMIÓN',dog:'PERRO',cat:'GATO',horse:'CABALLO',sheep:'OVEJA',cow:'VACA',elephant:'ELEFANTE',bear:'OSO',zebra:'CEBRA',giraffe:'JIRAFA'};
const vulnerable=new Set(['person','bicycle','motorcycle','dog','cat','horse','sheep','cow']);

function logCamera(s){cameraLog.push(`${new Date().toISOString()} — ${s}`);if(cameraLog.length>20)cameraLog=cameraLog.slice(-20)}
function resize(){const dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(innerWidth*dpr);canvas.height=Math.round(innerHeight*dpr);ctx.setTransform(dpr,0,0,dpr,0,0)}
addEventListener('resize',resize);resize();

function updateSound(){soundToggle.textContent=audioEnabled?'🔊 AUDIO':'🔇 AUDIO';soundToggle.className=`pill glass ${audioEnabled?'ok':'warn'}`}
async function activateAudio(){try{const AC=window.AudioContext||window.webkitAudioContext;if(!AC)throw new Error('Audio no disponible');if(!audioContext)audioContext=new AC();if(audioContext.state==='suspended')await audioContext.resume();audioError=''}catch(e){audioError=`${e.name||'Error'}: ${e.message||e}`}}
function tone(freq,t,dur,gain){if(!audioContext||audioContext.state!=='running')return;const o=audioContext.createOscillator(),g=audioContext.createGain();o.type='triangle';o.frequency.value=freq;g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(Math.min(gain,.96),t+.012);g.gain.exponentialRampToValueAtTime(.0001,t+dur);o.connect(g);g.connect(audioContext.destination);o.start(t);o.stop(t+dur+.02)}
function dangerBeep(){if(!audioEnabled||!audioContext||audioContext.state!=='running')return;const now=performance.now();if(lastRed&&now-lastBeep<1250)return;const t=audioContext.currentTime+.01;tone(880,t,.115,.72);tone(1120,t+.15,.115,.82);tone(1320,t+.30,.15,.90);lastBeep=now}

function stopCamera(){if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}video.srcObject=null}
function cameraName(mode){return mode==='environment'?'TRASERA':'FRONTAL'}
async function openCandidate(constraints,reason){logCamera(`Intento ${reason}`);const s=await navigator.mediaDevices.getUserMedia({audio:false,video:constraints});const track=s.getVideoTracks()[0];if(!track){s.getTracks().forEach(t=>t.stop());throw new Error('Sin pista de video')}stopCamera();stream=s;video.srcObject=s;video.muted=true;video.playsInline=true;video.setAttribute('playsinline','');await video.play();const settings=track.getSettings?track.getSettings():{};logCamera(`Activa: ${track.label||'sin nombre'} facing=${settings.facingMode||''}`);cameraState.textContent=`${cameraName(facingMode)} ✓`;cameraState.className='pill glass ok';cameraError='';resetZoom();return true}
async function startCamera(){stopCamera();cameraLog=[];cameraState.textContent=`${cameraName(facingMode)}…`;cameraState.className='pill glass warn';if(!isSecureContext||!navigator.mediaDevices?.getUserMedia){cameraError='La cámara requiere HTTPS y getUserMedia';cameraState.textContent='CAM ✕';cameraState.className='pill glass danger';return false}
 const tries=[
  [{facingMode:{exact:facingMode}},`facing exact ${facingMode}`],
  [{facingMode:{ideal:facingMode},width:{ideal:1280},height:{ideal:720}},`facing ideal ${facingMode}`],
  [true,'video genérico']
 ];
 let err=null;for(const [c,r] of tries){try{return await openCandidate(c,r)}catch(e){err=e;logCamera(`Falló ${r}: ${e.name||'Error'}: ${e.message||e}`)}}
 cameraError=err?`${err.name||'Error'}: ${err.message||err}`:'No se pudo abrir la cámara';cameraState.textContent='CAM ✕';cameraState.className='pill glass danger';return false}

function applyVideoTransform(){const mirror=facingMode==='user'?'scaleX(-1) ':'';video.style.transform=`translate(${focusPan.x.toFixed(2)}px,${focusPan.y.toFixed(2)}px) ${mirror}scale(${focusZoom.toFixed(4)})`}
function resetZoom(){focusZoom=cameraZoom;focusPan={x:0,y:0};dangerBox=null;dangerSeenAt=0;zoomToggle.textContent=`ZOOM ${cameraZoom===1?'1':cameraZoom===1.35?'1.35':cameraZoom.toFixed(1)}×`;zoomToggle.classList.remove('danger');applyVideoTransform();roadState={left:null,right:null,confidence:0,stable:0,lastAt:0}}
function updateDangerZoom(highest,sw,sh){const now=performance.now();if(highest?.risk.level==='ALTO'){dangerBox=highest.p.bbox;dangerSeenAt=now}const tracking=dangerBox&&now-dangerSeenAt<2100;let tz=cameraZoom,tx=0,ty=0;if(tracking){const vw=video.videoWidth||1280,vh=video.videoHeight||720;let[x,y,w,h]=dangerBox;if(facingMode==='user')x=vw-x-w;const cover=Math.max(sw/vw,sh/vh);const fit=Math.min(sw*.72/Math.max(w*cover,1),sh*.62/Math.max(h*cover,1));tz=Math.min(3.2,Math.max(cameraZoom*1.75,fit));const scale=Math.max(sw/vw,sh/vh)*tz;const maxX=Math.max(0,(tz-1)*sw*.48),maxY=Math.max(0,(tz-1)*sh*.44);tx=Math.max(-maxX,Math.min(maxX,-(x+w/2-vw/2)*scale));ty=Math.max(-maxY,Math.min(maxY,-(y+h/2-vh/2)*scale))}
 const blend=tracking?.20:.07;focusZoom+=(tz-focusZoom)*blend;focusPan.x+=(tx-focusPan.x)*blend;focusPan.y+=(ty-focusPan.y)*blend;if(!tracking&&Math.abs(focusZoom-cameraZoom)<.003){focusZoom=cameraZoom;focusPan={x:0,y:0};dangerBox=null}zoomToggle.textContent=tracking?`AUTO ${focusZoom.toFixed(1)}×`:`ZOOM ${cameraZoom===1?'1':cameraZoom===1.35?'1.35':cameraZoom.toFixed(1)}×`;zoomToggle.classList.toggle('danger',!!tracking);applyVideoTransform()}

function haversine(a,b,c,d){const R=6371000,r=Math.PI/180,p1=a*r,p2=c*r,dp=(c-a)*r,dl=(d-b)*r,q=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 2*R*Math.asin(Math.sqrt(q))}
function bearing(a,b,c,d){const r=Math.PI/180,p1=a*r,p2=c*r,dl=(d-b)*r,y=Math.sin(dl)*Math.cos(p2),x=Math.cos(p1)*Math.sin(p2)-Math.sin(p1)*Math.cos(p2)*Math.cos(dl);return( Math.atan2(y,x)/r+360)%360}
function startGPS(){if(!navigator.geolocation){geoError='Geolocalización no disponible';return}if(watchId!==null)navigator.geolocation.clearWatch(watchId);watchId=navigator.geolocation.watchPosition(p=>{const c=p.coords;let s=Number.isFinite(c.speed)?c.speed:null;if(s===null&&lastFix){const dt=(p.timestamp-lastFix.t)/1000;if(dt>.7&&dt<15){const dist=haversine(lastFix.lat,lastFix.lon,c.latitude,c.longitude);if(dist/dt<80)s=dist/dt}}let h=Number.isFinite(c.heading)?c.heading:null;if(h===null&&lastFix&&haversine(lastFix.lat,lastFix.lon,c.latitude,c.longitude)>3)h=bearing(lastFix.lat,lastFix.lon,c.latitude,c.longitude);gps={speed:s,heading:h,accuracy:Number.isFinite(c.accuracy)?c.accuracy:null,lat:c.latitude,lon:c.longitude};lastFix={lat:c.latitude,lon:c.longitude,t:p.timestamp};geoError='';updateHUD()},e=>{geoError=`${e.code}: ${e.message}`},{enableHighAccuracy:true,maximumAge:500,timeout:15000})}
async function sensorPermission(){try{if(typeof DeviceOrientationEvent!=='undefined'&&typeof DeviceOrientationEvent.requestPermission==='function'){const r=await DeviceOrientationEvent.requestPermission();if(r!=='granted')throw new Error('Permiso de orientación rechazado')}sensorError=''}catch(e){sensorError=e.message}}
function startSensors(){addEventListener('deviceorientation',e=>{if(Number.isFinite(e.alpha))orient.alpha=e.alpha;if(Number.isFinite(e.beta))orient.beta=e.beta;if(Number.isFinite(e.gamma))orient.gamma=e.gamma;updateHUD()},true)}
function updateHUD(){const k=Number.isFinite(gps.speed)?Math.max(0,gps.speed*3.6):null;speedEl.textContent=k===null?'--':k.toFixed(k<10?1:0);const h=Number.isFinite(gps.heading)?gps.heading:Number.isFinite(orient.alpha)?(360-orient.alpha)%360:null;headingEl.textContent=Number.isFinite(h)?`${Math.round(h)}°`:'--°';countEl.textContent=predictions.length}

async function loadAI(){aiState.textContent='IA…';aiState.className='pill glass warn';try{if(typeof tf==='undefined'||typeof cocoSsd==='undefined')throw new Error('TensorFlow/COCO-SSD no cargado');try{await tf.setBackend('webgl')}catch(_){}await tf.ready();model=await cocoSsd.load({base:'lite_mobilenet_v2'});aiState.textContent='IA ✓';aiState.className='pill glass ok';aiError='';scheduleDetect(100)}catch(e){aiError=`${e.name||'Error'}: ${e.message||e}`;aiState.textContent='IA ✕';aiState.className='pill glass danger'}}
function scheduleDetect(ms=260){clearTimeout(detectTimer);detectTimer=setTimeout(runDetect,ms)}
async function runDetect(){if(!model||!stream||detectBusy||video.readyState<2){scheduleDetect(300);return}detectBusy=true;try{const all=await model.detect(video,12,.42);predictions=all.filter(p=>relevant.has(p.class));aiError=''}catch(e){aiError=`${e.name||'Error'}: ${e.message||e}`}finally{detectBusy=false;updateHUD();scheduleDetect(260)}}

function videoToScreen(bbox){const vw=video.videoWidth||1280,vh=video.videoHeight||720,sw=innerWidth,sh=innerHeight,scale=Math.max(sw/vw,sh/vh)*focusZoom,dw=vw*scale,dh=vh*scale,ox=(sw-dw)/2,oy=(sh-dh)/2;let[x,y,w,h]=bbox;if(facingMode==='user')x=vw-x-w;return{x:ox+x*scale+focusPan.x,y:oy+y*scale+focusPan.y,w:w*scale,h:h*scale}}
function riskFor(b,cls){const sw=innerWidth,sh=innerHeight,cx=b.x+b.w/2,bottom=b.y+b.h,center=Math.abs(cx-sw/2)/(sw/2),area=(b.w*b.h)/(sw*sh),kmh=Number.isFinite(gps.speed)?gps.speed*3.6:0;let s=0;if(center<.20)s+=2;else if(center<.36)s++;if(area>.12)s+=2;else if(area>.04)s++;if(bottom>sh*.79)s+=2;else if(bottom>sh*.63)s++;if(kmh>25&&center<.28)s++;if(kmh>60&&center<.34)s++;if(vulnerable.has(cls)&&center<.42)s++;if(s>=6)return{level:'ALTO',color:'rgba(255,70,82,.98)',score:s};if(s>=4)return{level:'MEDIO',color:'rgba(255,205,64,.98)',score:s};return{level:'BAJO',color:'rgba(58,225,145,.94)',score:s}}
function marker(b,r){const{x,y,w,h}=b,len=Math.max(10,Math.min(24,Math.min(w,h)*.20));ctx.save();ctx.strokeStyle=r.color;ctx.lineWidth=r.level==='ALTO'?3.2:r.level==='MEDIO'?2.5:1.8;ctx.lineCap='round';if(r.level!=='BAJO'){ctx.shadowColor=r.color;ctx.shadowBlur=r.level==='ALTO'?9:4}ctx.beginPath();ctx.moveTo(x,y+len);ctx.lineTo(x,y);ctx.lineTo(x+len,y);ctx.moveTo(x+w-len,y);ctx.lineTo(x+w,y);ctx.lineTo(x+w,y+len);ctx.moveTo(x+w,y+h-len);ctx.lineTo(x+w,y+h);ctx.lineTo(x+w-len,y+h);ctx.moveTo(x+len,y+h);ctx.lineTo(x,y+h);ctx.lineTo(x,y+h-len);ctx.stroke();ctx.restore()}
function smallLabel(b,p,r){if(r.level==='BAJO')return;const n=labels[p.class]||p.class.toUpperCase();ctx.save();ctx.font='700 10px system-ui';const tw=ctx.measureText(n).width,pad=5,hh=18,x=Math.max(4,Math.min(innerWidth-tw-pad*2-4,b.x)),y=Math.max(hh+4,b.y-3);ctx.fillStyle='rgba(4,8,12,.62)';ctx.beginPath();if(ctx.roundRect)ctx.roundRect(x,y-hh,tw+pad*2,hh,7);else ctx.rect(x,y-hh,tw+pad*2,hh);ctx.fill();ctx.fillStyle=r.color;ctx.fillText(n,x+pad,y-5);ctx.restore()}

// V5.6: la primera fila de guía queda en 81% de la pantalla.
// Así se evita dibujar la línea sobre el capot o la zona inferior del parabrisas.
const PROBE_W=192,PROBE_H=112,ROAD_ROWS=[.81,.72,.64,.57],MIN_SPEED=5,ROAD_MIN_CONF=.40;
const probe=document.createElement('canvas');probe.width=PROBE_W;probe.height=PROBE_H;const pctx=probe.getContext('2d',{willReadFrequently:true});
let roadState={left:null,right:null,confidence:0,stable:0,lastAt:0};
function loseRoad(){roadState.confidence*=.68;roadState.stable=Math.max(0,roadState.stable-1);if(roadState.confidence<.15){roadState.left=null;roadState.right=null;roadState.stable=0}}
function updateRoad(sw,sh){const now=performance.now();if(!stream||video.readyState<2||now-roadState.lastAt<150)return;roadState.lastAt=now;const kmh=Number.isFinite(gps.speed)?gps.speed*3.6:0;if(kmh<MIN_SPEED){loseRoad();return}try{const vw=video.videoWidth||1280,vh=video.videoHeight||720,scale=Math.max(sw/vw,sh/vh)*focusZoom,cw=sw/scale,ch=sh/scale,cx=(vw-cw)/2-focusPan.x/scale,cy=(vh-ch)/2-focusPan.y/scale;pctx.drawImage(video,cx,cy,cw,ch,0,0,PROBE_W,PROBE_H);const px=pctx.getImageData(0,0,PROBE_W,PROBE_H).data;const lum=(x,y)=>{x=Math.max(0,Math.min(PROBE_W-1,x));y=Math.max(0,Math.min(PROBE_H-1,y));const i=(y*PROBE_W+x)*4;return px[i]*.299+px[i+1]*.587+px[i+2]*.114};
 const edge=(y,min,max,expected)=>{let best=null;for(let x=min;x<=max;x++){const a=lum(x+3,y)-lum(x-3,y),b=lum(x+3,y-2)-lum(x-3,y-2),c=lum(x+3,y+2)-lum(x-3,y+2),con=(Math.abs(a)+Math.abs(b)+Math.abs(c))/3,same=(Math.sign(a)===Math.sign(b)?1:0)+(Math.sign(a)===Math.sign(c)?1:0);if(con<12||same<1)continue;const score=con+same*7-Math.abs(x-expected)*.46;if(!best||score>best.score)best={x:x/PROBE_W,score,contrast:con}}return best};
 const L=[],R=[];for(let i=0;i<ROAD_ROWS.length;i++){const y=Math.round(PROBE_H*ROAD_ROWS[i]),n=i*.045,pl=roadState.left?.[i]?.x,pr=roadState.right?.[i]?.x,l=edge(y,9,90,Math.round(PROBE_W*(pl??(.25+n)))),r=edge(y,102,182,Math.round(PROBE_W*(pr??(.75-n))));if(!l||!r){loseRoad();return}L.push({...l,y:ROAD_ROWS[i]});R.push({...r,y:ROAD_ROWS[i]})}
 const widths=L.map((e,i)=>R[i].x-e.x),centers=L.map((e,i)=>(e.x+R[i].x)/2),conv=widths[0]-widths[3],drift=Math.max(...centers)-Math.min(...centers);if(widths[0]<.22||widths[0]>.94||widths[3]<.10||conv<.02||drift>.20){loseRoad();return}const avg=[...L,...R].reduce((s,e)=>s+e.contrast,0)/8,conf=Math.max(0,Math.min(1,avg/86+conv*.72));if(conf<ROAD_MIN_CONF){loseRoad();return}const blend=.32,smooth=(old,cur)=>cur.map((p,i)=>({x:old?.[i]?old[i].x*(1-blend)+p.x*blend:p.x,y:p.y}));roadState.left=smooth(roadState.left,L);roadState.right=smooth(roadState.right,R);roadState.confidence=roadState.stable?roadState.confidence*.58+conf*.42:conf;roadState.stable=Math.min(12,roadState.stable+1)}catch(e){loseRoad()}}
function trace(points,sw,sh){ctx.moveTo(points[0].x*sw,points[0].y*sh);for(let i=1;i<points.length-1;i++){const a=points[i],b=points[i+1];ctx.quadraticCurveTo(a.x*sw,a.y*sh,(a.x+b.x)*.5*sw,(a.y+b.y)*.5*sh)}const q=points[points.length-1];ctx.lineTo(q.x*sw,q.y*sh)}
function roadGuide(sw,sh){updateRoad(sw,sh);if(roadState.confidence<ROAD_MIN_CONF||roadState.stable<2||!roadState.left||!roadState.right)return;ctx.save();ctx.lineCap='round';ctx.lineJoin='round';ctx.setLineDash([]);const both=()=>{ctx.beginPath();trace(roadState.left,sw,sh);trace(roadState.right,sw,sh);ctx.stroke()};ctx.strokeStyle='rgba(255,255,255,.38)';ctx.lineWidth=9;both();ctx.strokeStyle='rgba(255,255,255,.99)';ctx.lineWidth=4.8;both();const center=roadState.left.map((p,i)=>({x:(p.x+roadState.right[i].x)/2,y:p.y}));ctx.strokeStyle='rgba(255,255,255,.18)';ctx.lineWidth=1.6;ctx.setLineDash([9,19]);ctx.beginPath();trace(center,sw,sh);ctx.stroke();ctx.restore()}

function draw(){const sw=innerWidth,sh=innerHeight;ctx.clearRect(0,0,sw,sh);roadGuide(sw,sh);const ranked=[];for(const p of predictions){const b=videoToScreen(p.bbox);if(b.x+b.w<0||b.y+b.h<0||b.x>sw||b.y>sh)continue;const r=riskFor(b,p.class),area=b.w*b.h/(sw*sh);if(r.level==='BAJO'&&area<.0045)continue;ranked.push({p,b,risk:r,area})}ranked.sort((a,b)=>b.risk.score-a.risk.score||b.p.score-a.p.score||b.area-a.area);const visible=ranked.slice(0,5),highest=visible[0]||null;updateDangerZoom(highest,sw,sh);for(const it of visible){marker(it.b,it.risk);smallLabel(it.b,it.p,it.risk)}const red=highest?.risk.level==='ALTO';if(red){dangerBeep();const n=labels[highest.p.class]||highest.p.class.toUpperCase();alertEl.textContent=`RIESGO • ${n}`;alertEl.style.color=highest.risk.color;alertEl.style.borderColor=highest.risk.color;alertEl.classList.add('show');flash.classList.add('active')}else{alertEl.classList.remove('show');flash.classList.remove('active')}lastRed=!!red;requestAnimationFrame(draw)}

async function startAll(){if(!isSecureContext||!navigator.mediaDevices?.getUserMedia){startText.textContent='La cámara sólo puede abrirse desde la versión HTTPS publicada en GitHub Pages.';startText.style.color='#ffd35a';startBtn.textContent='ABRIR PÁGINA SEGURA';startBtn.onclick=()=>location.href='https://jpsircelj-oss.github.io/anticolision360/v56.html';return}facingMode='environment';const a=activateAudio();start.style.display='none';hud.style.display='block';await startCamera();await a;updateSound();await sensorPermission();startSensors();startGPS();draw();loadAI()}
startBtn.addEventListener('click',startAll);
soundToggle.addEventListener('click',async()=>{audioEnabled=!audioEnabled;if(audioEnabled)await activateAudio();updateSound()});
zoomToggle.addEventListener('click',()=>{const i=ZOOMS.indexOf(cameraZoom);cameraZoom=ZOOMS[(i+1)%ZOOMS.length];resetZoom()});
$('switchCamera').addEventListener('click',async()=>{facingMode=facingMode==='environment'?'user':'environment';predictions=[];await startCamera()});
$('diagnostic').addEventListener('click',()=>{const track=stream?.getVideoTracks?.()[0];diagText.textContent=JSON.stringify({version:'AntiColisión 360 V5.6',secureContext:isSecureContext,url:location.href,camera:{requested:facingMode,active:!!stream,label:track?.label||'',settings:track?.getSettings?.()||{},error:cameraError,attempts:cameraLog},gps,orientation:orient,audio:{enabled:audioEnabled,state:audioContext?.state||'sin iniciar',error:audioError},roadGuide:{minimumSpeedKmh:MIN_SPEED,bottomLimitPercent:81,confidence:+roadState.confidence.toFixed(2),stableFrames:roadState.stable},ai:{loaded:!!model,backend:typeof tf!=='undefined'?tf.getBackend():null,predictions:predictions.map(p=>({class:p.class,score:+p.score.toFixed(3)})),error:aiError},errors:{geoError,sensorError},userAgent:navigator.userAgent},null,2);diag.style.display='block'});
$('closeDiag').addEventListener('click',()=>diag.style.display='none');
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&stream)video.play().catch(()=>{});if(audioEnabled&&audioContext?.state==='suspended')audioContext.resume().catch(()=>{})});
updateSound();
})();